config/routes.rb
Rails.application.routes.draw do
  #Ketan
  devise_for :employers, controllers: { application: 'application' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :employers, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
    resources :employers
    resources :companies
    resources :jobs
    resources :job_applies
    get 'download', to: 'job_applies#download', as: :download_file
    get 'rejected', to: 'job_applies#rejected', as: :rejected
    get 'job_seeker', to: 'job_applies#job_seeker', as: :job_seeker
    get 'total', to: 'job_applies#total', as: :total_job_applies
    resources :contact_people
    resources :industry_types
    resources :job_types
    resources :roles
    resources :cities
#Ketan

#pratik ---- all below
  resources :experiences
  get 'list', to: 'jobs#list', as: :alljob
  resources :educations
  resources :education_details
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root "users#home"
  resource :skills
  resources :locations
  resources :education_details
  resources :educations

  resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end
#post "/users/password" => "devise/passwords#create" ,as: "changepassword"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :employer
  belongs_to :industry_type
  belongs_to :city
  has_many :contact_people
  has_many :jobs
end

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  belongs_to :company
  belongs_to :role
  has_many :jobs
end

app/models/education.rb
class Education < ApplicationRecord
  has_one :job
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord

  belongs_to :user
  after_create :send_email

   def send_email
  #  UserMailer.welcome_email(@user).deliver_now
    #UserMailer.welcome_email(current_user).deliver_now  # for Sending Emails
   end


end

app/models/employer.rb
class Employer < ApplicationRecord

devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
belongs_to :role
has_many :companies
#Ketan Ankita
def update_with_password(params={})
if params[:password].blank?
    self.update_without_password(params)
  else
    self.verify_password_and_update(params)
  end
end

def update_without_password(params={})

   result = update_attributes(params)
   clean_up_passwords
   result
end

 def verify_password_and_update(params)
   #devises 'update_with_password'
   # https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb
   current_password = params.delete(:current_password)

   if params[:password].blank?
     params.delete(:password)
     params.delete(:password_confirmation) if params[:password_confirmation].blank?
   end

   result = if valid_password?(current_password)
     update_attributes(params)
   else
     self.attributes = params
     self.valid?
     self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
     false
   end

   clean_up_passwords
   result
 end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :skills

  #validates :designation,:company,:location,:skills, presence: true
  #validates :email, :contactnumber, presence: true, uniqueness: true

# ankita
  attr_reader :user_skills
# pratik
  def user_skills=(ids)
    self.skill_ids = ids.split(",")
  end

end

app/models/industry_type.rb
class IndustryType < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :job_type
  belongs_to :role
  belongs_to :education
  has_and_belongs_to_many :skills
  has_many :job_applies
  has_many :users, through: :job_applies

  attr_reader :user_skills
#Ketan
  before_save do
    if start_date<Date.today && end_date > Date.today
      self.status="Active"
    else
      self.status="Deactive"
    end
  end

  def status
      if self.start_date<Date.today && self.end_date > Date.today
        self.status="Active"
      else
        self.status="Deactive"
      end
  end

  def user_skills=(ids)
      self.skill_ids = ids.split(",")
  end

end

app/models/job_apply.rb
class JobApply < ApplicationRecord
  belongs_to :user
  belongs_to :job  
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :companies
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/ownskill.rb
class Ownskill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :industry_type
  has_many :employers
end

app/models/skill.rb
# pratik & ketan
class Skill < ApplicationRecord

  has_and_belongs_to_many :jobs
  has_and_belongs_to_many :experiences
end

app/models/user.rb
#pratik
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 validates :name, presence: true
 validates :email, :contactnumber, presence: true, uniqueness: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

         has_many :experiences, dependent: :destroy
         has_many :education_details
         has_many :job_applies
         has_many :jobs, through: :job_applies
         #has_and_belongs_to_many :jobs
         has_attached_file :resume
         validates_attachment :resume, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/jobs_controller.rb
#Riddhi
class JobsController < ApplicationController
  #Ketan
  def index
    ids=current_employer.companies.ids
    @jobs=Job.where(company_id: ids)
  end
#Ketan
#Pratik
  def list
    #@jobs =Job.find(params[:search])

    if params[:city_id]
      @jobs=Job.where(company_id: Company.where(city_id: params[:city_id],industry_type_id: params[:indu_id]),status: "Active")
        else
      @jobs=Job.all
    end
    @page=@jobs.page(params[:page]) # pagination  by Ankita

  end
#Pratik
  def new
	   @job=Job.new
  end
  def create
	  @job=Job.create(jobs_param)
  	if @job.save
  		redirect_to jobs_url
  	else
  		render "new"
  	end
  end
  def show

  	@job=Job.find(params[:id])
  end
  def destroy
  	@job=Job.find(params[:id])
  	@job.destroy
	  redirect_to jobs_url
  end

  def edit
	  @job = Job.find(params[:id])
  end
  def update
  	@job = Job.find(params[:id])
  	@job.update_attributes(jobs_param)
  	redirect_to jobs_url
  end

private
  def jobs_param
	   params.require(:job).permit(:company_id,:job_type_id,:role_id,:contact_person_id,:vacancy,:description,:salary,:address,:experience,:start_date,:end_date,:education_id,:status,:user_skills)
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_exps_helper.rb
module UserExpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<!-- Ketan -->
<%=form_for @job do |f|%>
<center><h3>Posting Job</h3></center>
<div class="form-group">
  <%=f.label("Select Company",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.collection_select(:company_id, current_employer.companies , :id, :name,{ include_blank: true },class:"form-control")%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Select Contact Person",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.grouped_collection_select(:contact_person_id,current_employer.companies.order(:name),:contact_people,:name, :id, :first_name,{ include_blank: true  },class:"form-control")%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Select Job Type",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.collection_select(:job_type_id, JobType.all, :id, :name,{ include_blank: false },class:"form-control")%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Select Role",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.collection_select(:role_id, Role.all, :id, :name,{ include_blank: false },class:"form-control")%>
  </div>
</div>
<br>
<br>

<div class="form-group">
  <%=f.label("Enter Total Vacancy",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.text_field :vacancy,class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Description",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%=f.text_area :description,class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Salary",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.text_field :salary,class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Address",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%=f.text_area :address,class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Experience",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%=f.select :experience,(0..30),{ include_blank: false },class:"form-control",class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("Start Date",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%=f.date_field :start_date,class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%=f.label("End Date",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%=f.date_field :end_date,class:"form-control"%>
  </div>
</div>
<br>
<br>
<div class="form-group">

  <%=f.label("Education",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.collection_select(:education_id, Education.all, :id, :qualification,{ include_blank: false },class:"form-control")%>
  </div>
</div>
<br>
<br>
<div class="form-group">
  <%= f.label(:skills ,"Skill",class:"col-sm-2 control-label") %>
  <div class="col-sm-6">
    <%= f.text_field :user_skills,class:"form-control","data-pre" => @job.skills.map(&:attributes).to_json %>
  </div>
</div>



<div class="form-group">
  <td><%=f.submit class: "btn btn-success btn-mini"%></td>
</div>

<%end%>

app/views/jobs/edit.html.erb
<!-- Ketan -->
<%=render "form"%>

app/views/jobs/index.html.erb
<!-- Riddhi -->
<html>
  <body>
    <center><h3>Total Posted Job </h3></center>
    <table class="table table-striped">
      <tr>
        <th><center>Posted Date</center></th>
        <th><center>Company</center></th>
        <th><center>Job Type</center></th>
        <th><center>Role</center></th>
        <th><center>Vacancy</center></th>
        <th><center>Description</center></th>
        <th><center>Salary</center></th>
        <th><center>Start Date</center></th>
        <th><center>End Date</center></th>
        <th><center>Status</center></th>
        <th><center>Action</center></th>
      </tr>
      <%@jobs.each do |job|%>

      <!--Ketan  -->
      <tr align="center">
        <td><%=job.created_at.strftime("%Y-%m-%d")%></td>
          <td>
          <ul><%=job.company.name%></ul>
          <ul><span class="blue"><%=job.job_applies.where(seen: false).count%></span><font color="blue">New Applies</font></ul>
          <ul><font color="#0645AD"><%=job.job_applies.where(rejected: false).count%></font><%=link_to 'Total Applied',job_applies_path(jobid: job.id),{ :class => "css_class" }%></ul>
        </td>
        <!--Ketan  -->
        <td><%=job.job_type.name%></td>
        <td><%=job.role.name%></td>
        <td><%=job.vacancy%></td>
        <td><%=job.description%></td>
        <td><%=job.salary%></td>
        <td><%=job.start_date%></td>
        <td><%=job.end_date%></td>
        <td><%=job.status%></td>
        <td>
          <ul><%= link_to "Show",job %></ul>
          <ul><%= link_to "Edit", edit_job_path(job) %></ul>
      		<ul><%= link_to "Delete",job,method: :delete, data:{confirm: "Are you sure to delete?"} %></ul>
        </td>
      </tr>
      <%end%>
    </table>
    <%=link_to "Add Job Post" , new_job_path %>
  </body>
</html>

app/views/jobs/list.html.erb
<!-- Ankita -->

<h1> List of All Jobs </h1>
<%=form_tag alljob_path, :method => 'get' do %>
  <p>
    <%= select_tag "city_id", options_from_collection_for_select(City.all, "id", "name",params[:city_id]) %>
      <%= select_tag "indu_id", options_from_collection_for_select(IndustryType.all, "id", "name",params[:indu_id]) %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= paginate @page%>
<%@jobs.each do |job|%>
<%= link_to job do %>
<div class="row">
  <div class="col-sm-8" style="background-color:white;">
    <div class="panel panel-default">
      <div class="panel-heading"><%=job.role.name%></div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-8" style="background-color:lavender;">
            company name : <%=job.company.name%>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4" style="background-color:lavender;">
            <span class="glyphicon glyphicon-briefcase"></span>
              Experience : <%=job.experience%> years +
          </div>
          <div class="col-sm-4" style="background-color:lavender;">
          location : <%= City.find(Company.find(job.company_id).city_id).id %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-8" style="background-color:lavender;">
           Skills Needs : &nbsp;&nbsp;&nbsp;
           <%job.skills.each do |skill| %>
              ' <%= skill.name %> ' &nbsp;&nbsp;&nbsp;
           <%end%>
           </div>
        </div>
      </div>

      <div class="panel-footer"> salary : <%=job.salary%> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Posted By :<%= Employer.find(Company.find(job.company_id).employer_id).first_name %>
      </div>
    </div>
  </div>
</div>
<%end%>
<%end%>

app/views/jobs/new.html.erb
<!-- Ketan -->
<%=render "form"%>

app/views/jobs/show.html.erb
<!-- Ketan -->
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Company name : <%=@job.company.name%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Job Type : <%=@job.job_type.name%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Role : <%=@job.role.name%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Vacancy : <%=@job.vacancy%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Description : <%=@job.description%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Salary : <%=@job.salary%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5><address>Address : <%=@job.address%></address></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Experience : <%=@job.experience%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Start Date : <%=@job.start_date%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>End Date : <%=@job.end_date%></h5>
  </div>
</div>
<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">

    <h5>Qualification : <%=@job.education.qualification%></h5>

  </div>
</div>

<div class="row">
  <div class="col-sm-8" style="background-color:lavender;">
    <h5>Status : <%=@job.status%></h5>
  </div>
</div>

<%if current_user %>
<p><br>
    <%= link_to "<button class='btn btn-success'>Apply</button>".html_safe, new_job_apply_path(jobid: @job.id)%></div>
</p>
<%end%>