config/routes.rb
Rails.application.routes.draw do
  #Ketan
  devise_for :employers, controllers: { application: 'application' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :employers, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
    resources :employers
    resources :companies
    resources :jobs
    resources :job_applies
    get 'download', to: 'job_applies#download', as: :download_file
    get 'rejected', to: 'job_applies#rejected', as: :rejected
    get 'job_seeker', to: 'job_applies#job_seeker', as: :job_seeker
    get 'total', to: 'job_applies#total', as: :total_job_applies
    resources :contact_people
    resources :industry_types
    resources :job_types
    resources :roles
    resources :cities
#Ketan

#pratik ---- all below
  resources :experiences
  get 'list', to: 'jobs#list', as: :alljob
  resources :educations
  resources :education_details
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root "users#home"
  resource :skills
  resources :locations
  resources :education_details
  resources :educations

  resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end
#post "/users/password" => "devise/passwords#create" ,as: "changepassword"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :employer
  belongs_to :industry_type
  belongs_to :city
  has_many :contact_people
  has_many :jobs
end

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  belongs_to :company
  belongs_to :role
  has_many :jobs
end

app/models/education.rb
class Education < ApplicationRecord
  has_one :job
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord

  belongs_to :user
  after_create :send_email

   def send_email
  #  UserMailer.welcome_email(@user).deliver_now
    #UserMailer.welcome_email(current_user).deliver_now  # for Sending Emails
   end


end

app/models/employer.rb
class Employer < ApplicationRecord

devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
belongs_to :role
has_many :companies
#Ketan Ankita
def update_with_password(params={})
if params[:password].blank?
    self.update_without_password(params)
  else
    self.verify_password_and_update(params)
  end
end

def update_without_password(params={})

   result = update_attributes(params)
   clean_up_passwords
   result
end

 def verify_password_and_update(params)
   #devises 'update_with_password'
   # https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb
   current_password = params.delete(:current_password)

   if params[:password].blank?
     params.delete(:password)
     params.delete(:password_confirmation) if params[:password_confirmation].blank?
   end

   result = if valid_password?(current_password)
     update_attributes(params)
   else
     self.attributes = params
     self.valid?
     self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
     false
   end

   clean_up_passwords
   result
 end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :skills

  #validates :designation,:company,:location,:skills, presence: true
  #validates :email, :contactnumber, presence: true, uniqueness: true

# ankita
  attr_reader :user_skills
# pratik
  def user_skills=(ids)
    self.skill_ids = ids.split(",")
  end

end

app/models/industry_type.rb
class IndustryType < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :job_type
  belongs_to :role
  belongs_to :education
  has_and_belongs_to_many :skills
  has_many :job_applies
  has_many :users, through: :job_applies

  attr_reader :user_skills
#Ketan
  before_save do
    if start_date<Date.today && end_date > Date.today
      self.status="Active"
    else
      self.status="Deactive"
    end
  end

  def status
      if self.start_date<Date.today && self.end_date > Date.today
        self.status="Active"
      else
        self.status="Deactive"
      end
  end

  def user_skills=(ids)
      self.skill_ids = ids.split(",")
  end

end

app/models/job_apply.rb
class JobApply < ApplicationRecord
  belongs_to :user
  belongs_to :job  
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :companies
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/ownskill.rb
class Ownskill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :industry_type
  has_many :employers
end

app/models/skill.rb
# pratik & ketan
class Skill < ApplicationRecord

  has_and_belongs_to_many :jobs
  has_and_belongs_to_many :experiences
end

app/models/user.rb
#pratik
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 validates :name, presence: true
 validates :email, :contactnumber, presence: true, uniqueness: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

         has_many :experiences, dependent: :destroy
         has_many :education_details
         has_many :job_applies
         has_many :jobs, through: :job_applies
         #has_and_belongs_to_many :jobs
         has_attached_file :resume
         validates_attachment :resume, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_exps_helper.rb
module UserExpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_navbar.html.erb
<!--Ketan  -->
<% if current_employer %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bacancytechnology</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if employer_signed_in? %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <% if current_employer.companies.count>0%>
                <li><%= link_to "Show", companies_url  %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contact Person <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Add Contact Person",new_contact_person_path %></li>
                    <% if ContactPerson.where(company_id: current_employer.companies).count>0%>
                      <li role="separator" class="divider"></li>
                      <li><%=link_to "Show Contact Person", contact_people_path %></li>
                    <%end%>
                  </ul>
                </li>

                  <% if ContactPerson.where(company_id: current_employer.companies).count>0%>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Job Post <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Add New Post",new_job_path%></li>
                    <% if Job.where(company_id: current_employer.companies).count>0%>
                      <li role="separator" class="divider"></li>
                      <li><%=link_to "Show Posted Job", jobs_path %></li>
                    <%end%>
                  </ul>
                </li>
                <% end %>

          <%else%>
                  <li><%= link_to "Add Company", new_company_path %></li>
          <%end%>
      </ul>
      <%end%>
      <form class="navbar-form navbar-left" >
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if employer_signed_in? %>
        <li> <%= link_to current_employer.email ,edit_employer_registration_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_employer.first_name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Edit Profile",edit_employer_registration_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%=link_to "Change Password",edit_employer_path(current_employer) %></li>
                  </ul>
                </li>
        <li> <%= link_to "Logout", destroy_employer_session_path,method: :delete %></li>

        <% else %>
        <li><%= link_to "Sign Up",new_employer_registration_path %></li>
        <li><%= link_to "Login",new_employer_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--Ketan  -->
<%elsif current_user%>

<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">One Job Street</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jobs<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%=link_to "All Jobs ", alljob_path %></li>
          <li><a href="#">search by location</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Companies <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Other <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <!-- <form class="navbar-form navbar-left" >
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%=link_to "Edit Profile",edit_user_registration_path %></li>
                  <li><%=link_to "Edit Education",edit_education_detail_path(current_user) %></li>

                  <% if current_user.hasexp? %>
                      <li><%=link_to "Edit Employeement",edit_experience_path(current_user) %></li>
                  <% else %>
                      <li><%=link_to "Add Employeement",new_experience_path %></li>
                  <% end %>

                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Change your password", edit_user_path(current_user) %></li>
                </ul>
              </li>
      <li> <%= link_to "Logout", destroy_user_session_path,method: :delete %></li>

      <% else %>
      <!--Riddhi  -->

            <li><%= link_to "Jobseeker Panel",new_user_session_path,class: "glyphicon glyphicon-log-in" %></li>
            <li><%= link_to "Recruiter Panel",new_employer_session_path,class: "glyphicon glyphicon-log-in" %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<%else %>
<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">One Job Street</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
      <li><a href="#">About Us</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Jobseeker Panel",new_user_session_path %></li>
          <li><%= link_to "Recruiter Panel",new_employer_session_path%></li>
      </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<%end %>

app/views/shared/_reqruiter_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">One Job Street</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jobs<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">All jobs</a></li>
          <li><a href="#">search by location</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Companies <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Other <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <!-- <form class="navbar-form navbar-left" >
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%=link_to "Edit Profile",edit_user_registration_path %></li>
                  <li><%=link_to "Edit Education",edit_education_detail_path(current_user) %></li>

                  <% if current_user.hasexp? %>
                      <li><%=link_to "Edit Employeement",edit_experience_path(current_user) %></li>
                  <% else %>
                      <li><%=link_to "Add Employeement",new_experience_path %></li>
                  <% end %>

                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Change your password", edit_user_path(current_user) %></li>
                </ul>
              </li>
      <li> <%= link_to "Logout", destroy_user_session_path,method: :delete %></li>

      <% else %>
            <li><%= link_to "SignUp",new_user_registration_path,class:"glyphicon glyphicon-user"%></li>
            <li><%= link_to "Login",new_user_session_path,class: "glyphicon glyphicon-log-in" %></li>
            <li><%= link_to "Recruiterpanel",,class: "glyphicon glyphicon-log-in" %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>