config/routes.rb
Rails.application.routes.draw do
  #Ketan
  devise_for :employers, controllers: { application: 'application' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :employers, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
    resources :employers
    resources :companies
    resources :jobs
    resources :job_applies
    get 'download', to: 'job_applies#download', as: :download_file
    get 'rejected', to: 'job_applies#rejected', as: :rejected
    get 'job_seeker', to: 'job_applies#job_seeker', as: :job_seeker
    get 'total', to: 'job_applies#total', as: :total_job_applies
    resources :contact_people
    resources :industry_types
    resources :job_types
    resources :roles
    resources :cities
#Ketan

#pratik ---- all below
  resources :experiences
  get 'list', to: 'jobs#list', as: :alljob
  resources :educations
  resources :education_details
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root "users#home"
  resource :skills
  resources :locations
  resources :education_details
  resources :educations

  resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end
#post "/users/password" => "devise/passwords#create" ,as: "changepassword"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :employer
  belongs_to :industry_type
  belongs_to :city
  has_many :contact_people
  has_many :jobs
end

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  belongs_to :company
  belongs_to :role
  has_many :jobs
end

app/models/education.rb
class Education < ApplicationRecord
  has_one :job
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord

  belongs_to :user
  after_create :send_email

   def send_email
  #  UserMailer.welcome_email(@user).deliver_now
    #UserMailer.welcome_email(current_user).deliver_now  # for Sending Emails
   end


end

app/models/employer.rb
class Employer < ApplicationRecord

devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
belongs_to :role
has_many :companies
#Ketan Ankita
def update_with_password(params={})
if params[:password].blank?
    self.update_without_password(params)
  else
    self.verify_password_and_update(params)
  end
end

def update_without_password(params={})

   result = update_attributes(params)
   clean_up_passwords
   result
end

 def verify_password_and_update(params)
   #devises 'update_with_password'
   # https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb
   current_password = params.delete(:current_password)

   if params[:password].blank?
     params.delete(:password)
     params.delete(:password_confirmation) if params[:password_confirmation].blank?
   end

   result = if valid_password?(current_password)
     update_attributes(params)
   else
     self.attributes = params
     self.valid?
     self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
     false
   end

   clean_up_passwords
   result
 end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :skills

  #validates :designation,:company,:location,:skills, presence: true
  #validates :email, :contactnumber, presence: true, uniqueness: true

# ankita
  attr_reader :user_skills
# pratik
  def user_skills=(ids)
    self.skill_ids = ids.split(",")
  end

end

app/models/industry_type.rb
class IndustryType < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :job_type
  belongs_to :role
  belongs_to :education
  has_and_belongs_to_many :skills
  has_many :job_applies
  has_many :users, through: :job_applies

  attr_reader :user_skills
#Ketan
  before_save do
    if start_date<Date.today && end_date > Date.today
      self.status="Active"
    else
      self.status="Deactive"
    end
  end

  def status
      if self.start_date<Date.today && self.end_date > Date.today
        self.status="Active"
      else
        self.status="Deactive"
      end
  end

  def user_skills=(ids)
      self.skill_ids = ids.split(",")
  end

end

app/models/job_apply.rb
class JobApply < ApplicationRecord
  belongs_to :user
  belongs_to :job  
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :companies
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/ownskill.rb
class Ownskill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :industry_type
  has_many :employers
end

app/models/skill.rb
# pratik & ketan
class Skill < ApplicationRecord

  has_and_belongs_to_many :jobs
  has_and_belongs_to_many :experiences
end

app/models/user.rb
#pratik
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 validates :name, presence: true
 validates :email, :contactnumber, presence: true, uniqueness: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

         has_many :experiences, dependent: :destroy
         has_many :education_details
         has_many :job_applies
         has_many :jobs, through: :job_applies
         #has_and_belongs_to_many :jobs
         has_attached_file :resume
         validates_attachment :resume, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/companies_controller.rb
#Riddhi
class CompaniesController < ApplicationController
#Ketan
before_action :set_company, only: [:show, :edit, :update, :destroy]
  def set_company
    @company=Company.find(params[:id])
  end
  #ketan
  def index
    @companies=current_employer.companies
  end
  def show
  end
  def new
    @company=Company.new
  end
  def create
    @company=current_employer.companies.create(company_params)
    if @company.save
      redirect_to company_path(@company)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @company.update_attributes(company_params)
      redirect_to company_path(@company)
    else
      render "edit"
    end
  end
  private
  def company_params
    params.require(:company).permit(:name,:website,:industry_type_id,:description,:address,:city_id,:contact,:email,:google_plus,:facebook,:linkedin)
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_exps_helper.rb
module UserExpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<!-- Riddhi -->
<%=form_for @company do |f|%>
<center>
<h2>Enter Company Details</h2>
<div class="form-group">
  <%=f.label("Company Name",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :name,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Website",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :website,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Select Industry",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%= f.collection_select(:industry_type_id, IndustryType.all, :id, :name,{ include_blank: false }, class: "form-control")%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Description",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_area :description,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Address",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_area :address,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Select City",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.collection_select(:city_id,City.all,:id,:name,{ include_blank: false }, class: "form-control")%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Contact",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :contact,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Email",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :email,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Goole Plus",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :google_plus,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Linked In",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :linkedin,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <%=f.label("Facebook",class: "col-sm-2 control-label") %>
  <div class="col-sm-8">
    <%=f.text_field :facebook,class:"form-control"%>
  </div>
</div>

<br><br>

<div class="form-group">
  <div class="col-sm-8">
    <%= f.submit class: "btn btn-success btn-mini"%>
  </div>
</div>

<br><br>

</center>
<%end%>

app/views/companies/edit.html.erb
<!-- Riddhi -->
<%= render "form"%>

app/views/companies/index.html.erb
<!-- Riddhi -->
<table class="table table-striped">
  <tr>
    <th>Company Name</th>
    <th>Industrt Type</th>
    <th>Address</th>
    <th>City</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Action</th>
  </tr>
  <% @companies.each do |company|%>
  <tr>
    <td><%=company.name%></td>
    <td><%=company.industry_type.name%></td>
    <td><%=company.address%></td>
    <td><%=company.city.name%></td>
    <td><%=company.contact%></td>
    <td><%=company.email%></td>
    <td>
      <%=link_to "View Profile",company%>
      <%=link_to "Edit",edit_company_path(company)%>
      <%=link_to "Delete",company,method: :Delete%>
    </td>
  </tr>
  <%end%>
</table>

<%= link_to "Add New Company",new_company_path%>

app/views/companies/new.html.erb
<!-- Riddhi -->
<%= render "form"%>

app/views/companies/show.html.erb
<!-- Riddhi -->
<table class="table table-striped">
  <tr>
    <td>Employer Name</td>
    <td><%=@company.employer.first_name%></td>
  </tr>
  <tr>
    <td>Website</td>
    <td><%=@company.website%></td>
  </tr>
  <tr>
    <td>Industry</td>
    <td><%=@company.industry_type.name%></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%=@company.description%></td>
  </tr>
  <tr>
    <td>Address</td>
    <td><%=@company.address%></td>
  </tr>
  <tr>
    <td>City</td>
    <td><%=@company.city.name%></td>
  </tr>
  <tr>
    <td>Contact</td>
    <td><%=@company.contact%></td>
  </tr>
  <tr>
    <td>Website</td>
    <td><%=@company.email%></td>
  </tr>
  <tr>
    <td>Google Plus</td>
    <td><%=@company.google_plus%></td>
  </tr>
  <tr>
    <td>Linkedin</td>
    <td><%=@company.linkedin%></td>
  </tr>
  <tr>
    <td>Facebook</td>
    <td><%=@company.facebook%></td>
  </tr>
</table>

<%= link_to "Edit" ,edit_company_path(@company)%>
<%= link_to "Add Contact Person For this Company" ,new_contact_person_path%>