config/routes.rb
Rails.application.routes.draw do
  #Ketan
  devise_for :employers, controllers: { application: 'application' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :employers, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
    resources :employers
    resources :companies
    resources :jobs
    resources :job_applies
    get 'download', to: 'job_applies#download', as: :download_file
    get 'rejected', to: 'job_applies#rejected', as: :rejected
    get 'job_seeker', to: 'job_applies#job_seeker', as: :job_seeker
    get 'total', to: 'job_applies#total', as: :total_job_applies
    resources :contact_people
    resources :industry_types
    resources :job_types
    resources :roles
    resources :cities
#Ketan

#pratik ---- all below
  resources :experiences
  get 'list', to: 'jobs#list', as: :alljob
  resources :educations
  resources :education_details
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root "users#home"
  resource :skills
  resources :locations
  resources :education_details
  resources :educations

  resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end
#post "/users/password" => "devise/passwords#create" ,as: "changepassword"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :employer
  belongs_to :industry_type
  belongs_to :city
  has_many :contact_people
  has_many :jobs
end

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  belongs_to :company
  belongs_to :role
  has_many :jobs
end

app/models/education.rb
class Education < ApplicationRecord
  has_one :job
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord

  belongs_to :user
  after_create :send_email

   def send_email
  #  UserMailer.welcome_email(@user).deliver_now
    #UserMailer.welcome_email(current_user).deliver_now  # for Sending Emails
   end


end

app/models/employer.rb
class Employer < ApplicationRecord

devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
belongs_to :role
has_many :companies
#Ketan Ankita
def update_with_password(params={})
if params[:password].blank?
    self.update_without_password(params)
  else
    self.verify_password_and_update(params)
  end
end

def update_without_password(params={})

   result = update_attributes(params)
   clean_up_passwords
   result
end

 def verify_password_and_update(params)
   #devises 'update_with_password'
   # https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb
   current_password = params.delete(:current_password)

   if params[:password].blank?
     params.delete(:password)
     params.delete(:password_confirmation) if params[:password_confirmation].blank?
   end

   result = if valid_password?(current_password)
     update_attributes(params)
   else
     self.attributes = params
     self.valid?
     self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
     false
   end

   clean_up_passwords
   result
 end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :skills

  #validates :designation,:company,:location,:skills, presence: true
  #validates :email, :contactnumber, presence: true, uniqueness: true

# ankita
  attr_reader :user_skills
# pratik
  def user_skills=(ids)
    self.skill_ids = ids.split(",")
  end

end

app/models/industry_type.rb
class IndustryType < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :job_type
  belongs_to :role
  belongs_to :education
  has_and_belongs_to_many :skills
  has_many :job_applies
  has_many :users, through: :job_applies

  attr_reader :user_skills
#Ketan
  before_save do
    if start_date<Date.today && end_date > Date.today
      self.status="Active"
    else
      self.status="Deactive"
    end
  end

  def status
      if self.start_date<Date.today && self.end_date > Date.today
        self.status="Active"
      else
        self.status="Deactive"
      end
  end

  def user_skills=(ids)
      self.skill_ids = ids.split(",")
  end

end

app/models/job_apply.rb
class JobApply < ApplicationRecord
  belongs_to :user
  belongs_to :job  
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :companies
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/ownskill.rb
class Ownskill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :industry_type
  has_many :employers
end

app/models/skill.rb
# pratik & ketan
class Skill < ApplicationRecord

  has_and_belongs_to_many :jobs
  has_and_belongs_to_many :experiences
end

app/models/user.rb
#pratik
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 validates :name, presence: true
 validates :email, :contactnumber, presence: true, uniqueness: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

         has_many :experiences, dependent: :destroy
         has_many :education_details
         has_many :job_applies
         has_many :jobs, through: :job_applies
         #has_and_belongs_to_many :jobs
         has_attached_file :resume
         validates_attachment :resume, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/education_details_controller.rb
# Anktia

class EducationDetailsController < ApplicationController
  def index
    @education_details=EducationDetail.all
  end
  def new
    @education_detail=EducationDetail.new
  end

  def create
    @education_details=current_user.education_details.new(education_details_param)
      if @education_details.save
        flash[:notice] = "Education Details save successfully..!"
# pratik
        # client = Twilio::REST::Client.new ENV["TWILIO_SID"], ENV["TWILIO_TOKEN"]
        # client.account.sms.messages.create(
        # from: ENV["TWILIO_PHONE_NUMBER"],
        # to: "+917016230268",
        # body: "hi welcome to onejobstreet")
        #
        redirect_to education_details_url
      else
        render "new"
      end
  end

  def edit
     @education_detail=EducationDetail.find_by(user_id: current_user.id)
  end
  def update
    @education_detail = EducationDetail.find_by(id: params[:id])
    @use=current_user
    if @education_detail.update(education_details_param)

      UserMailer.welcome_email(current_user).deliver_now  # for Sending Emails

      flash[:notice] = "Education Details Update successfully..!"
      redirect_to users_url
    else

      render "edit"
    end
  end
  def destroy
    @education_detail=EducationDetail.find_by(id: params[:id])
    if @education_detail.destroy
      redirect_to education_details_url
    end
  end
  private
  def education_details_param
    params.require(:education_detail).permit(:qualification,:course,:specialization,:college,:course_type,:passing_year)
  end
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_exps_helper.rb
module UserExpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/education_details/_form.html.erb
<!-- pratik ankita -->

<%= form_for  @education_detail  do |f| %>
<h2 align="center" ><span class="glyphicon glyphicon-education"></span> Education Details </h2>
<div class="form-group">

                <%= f.label("Highest Qualification :") %>
                  <div class="input-group">
                    <%= f.select :qualification, Education.all.collect {|p| [ p.qualification, p.id ] }, { include_blank: true },class:"input-small form-control" %>
                  <!--  <input type="text" class="input-small form-control"name="start" /> -->
                     <span class="input-group-addon">Education</span>
                    <%= f.select :passing_year,1960..2020, { include_blank: true },class:"input-small form-control" %>
                  </div>
                  <span class="input-group-addon">Passing Years</span>
              </div>

  <div class="form-group">
    <%= f.label("Course :") %>
    <%= f.text_field :course,class:"form-control",required: true %>
  </div>
  <div class="form-group">
  <%= f.label("Specialization :") %>
  <%= f.text_field :specialization,class:"form-control",required: true%>
  </div>
<div class="form-group">

  <%= f.label("College / University :") %>
  <%= f.text_field :college,class:"form-control",required: true %>
</div>

<div class="form-group">
  <%= f.label("Course type :") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button(:course_type,"part time")%>
  <%= f.label(:course_type_part,"Part Time")%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button(:course_type,"full time")%>
  <%= f.label(:course_type_full,"Full Time")%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button(:course_type,"correspondence")%>
  <%= f.label(:course_type_correspondent,"Correspondence")%><br>
</div>



<div class="form-group">
  <div class="col-xs-4 col-md-3 "><%= f.submit "Submit", class:"btn btn-primary btn-block btn-lg", tabindex:"7" %></div>
    </div>
<% end %>

    <div class="form-group">
   <div class="col-xs-4 col-md-3 ">
    <%= link_to new_education_detail_path, class: "btn btn-success btn-block btn-lg" do %>
    <i class="glyphicon glyphicon-plus"></i> Add More Education
<% end %>
</div>
</div>

app/views/education_details/edit.html.erb
<%= render "form"%>

app/views/education_details/index.html.erb
<% @education_details.each do |e| %>
  <br/><br/>Highest Qualification :<%= e.qualification %>
  <br/>Course :<%= e.course %>
  <br/>Specialization :<%= e.specialization %>
  <br/>College / University :<%= e.college %>
  <br/>Course type :<%= e.course_type %>
  <br/>Passing year :<%= e.passing_year %><br/><br/>
  <%= link_to "Edit" , edit_education_detail_path(e) %> &nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to "Delete",education_detail_path(e), method: :delete, data: { confirm: 'Are you sure?' }%><br /><br />
<% end %>
<br><br><br><%= link_to "Back" , new_education_detail_path %>

app/views/education_details/new.html.erb
<%= render "form"%>